### ISSUE TITLE
Possible to create a downstream proxy?

### ISSUE THREAD

**Issue by mpet** [trekawek/toxiproxy-java#100]
Hi,

We have the following setup:

NETCONF java client <-- ToxiProxy <-- NETCONF c++ server 

We are using testcontainers to test.

1, We setup a NETCONF client to listen on port 4335.
2. We create a ToxiProxy instance using:
```
 final ToxiproxyClient toxiproxyClient = new ToxiproxyClient(TOXIPROXY.getHost(), TOXIPROXY.getControlPort());
 proxy = toxiproxyClient.createProxy("netconfclient",  TOXIPROXY.getHost()+":" + TOXI_PROXI_PORT,
	        		"host.testcontainers.internal+":" + 4335):
```
4. Trigger NETCONF server to connect to NETCONF client. And we can see it is successful.
 
```
Successfully connected to host.testcontainers.internal:4335 over IPv4.
```

5. Then I try to close connection using a toxic like this:

 ```
	        proxy .toxics().bandwidth("CUT_CONNECTION_DOWNSTREAM", ToxicDirection.DOWNSTREAM, 0);
	        proxy .toxics().bandwidth("CUT_CONNECTION_UPSTREAM", ToxicDirection.UPSTREAM, 0);
	        //try and pefrom operation over the connection and it is still possible but it should not!!!!
	       
	        proxy .toxics().get("CUT_CONNECTION_UPSTREAM").remove();
	        proxy .toxics().get("CUT_CONNECTION_DOWNSTREAM").remove();
```
Is there a way to check the toxiproxy and that it is acutally used?

**Comment by trekawek** [comment]
Hi @mpet. From what you wrote here:
```java
 proxy = toxiproxyClient.createProxy("netconfclient",  TOXIPROXY.getHost()+":" + TOXI_PROXI_PORT,
	        		"host.testcontainers.internal+":" + 4335):
```
it seems that Toxiproxy listens on `TOXIPROXY.getHost()+":" + TOXI_PROXI_PORT` and forwards the traffic to `host.testcontainers.internal:4335`.

If that's the case, you should try to connect to the `TOXIPROXY.getHost()+":" + TOXI_PROXI_PORT`, not directly to the `host.testcontainers.internal:4335`. The latter doesn't know anything about toxiproxy, it's just your service running normally.
