### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by davidkuster** [trekawek/toxiproxy-java#11]
I assume it's just an oversight, but can you add a license to this repo? I just discovered Toxiproxy and being in a Java shop this client seems like the best option to use it, but without a license I'm sure the dependency will get flagged by a CI scan somewhere along the line.

See [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/).

Thanks!

**Comment by trekawek** [comment]
Good point, thanks. I've added the ASF 2.0 license, hope it'll work for you.

**Comment by davidkuster** [comment]
Should be great. Thanks for the quick response!
