### ISSUE TITLE
Add support for a toxiproxy server hosted on a HTTPS endpoint

### ISSUE THREAD

**Issue by davidh87** [trekawek/toxiproxy-java#12]
The ToxiproxyClient constructs a HttpClient with a provided hostname and port; however, within the HttpClient there is the assumption that endpoints are always HTTP regardless of port. Would be great to add support for constructing the ToxiproxyClient with support for the actual toxiproxy server being hosted on a HTTPS endpoint.

I'm happy to raise PR if this repo is still active?

**Comment by trekawek** [comment]
@davidh87 - yes, it's active. PR's are welcome!
