### ISSUE TITLE
groupId in README.MD is incorrect

### ISSUE THREAD

**Issue by imalygin** [trekawek/toxiproxy-java#2]
Currently README.MD has following Maven dependency description:

`<dependency>`
 ` <groupId>eu.rekawek</groupId>`
 `<artifactId>toxiproxy-java</artifactId>`
 ` <version>2.0</version>`
`</dependency>`

groupId is 'eu.rekawek' but it should be 'eu.rekawek.toxiproxy'.

**Comment by trekawek** [comment]
Thanks! Fixed.
