### ISSUE TITLE
NPE is thrown when calling ToxicLists get method

### ISSUE THREAD

**Issue by lordofthejars** [trekawek/toxiproxy-java#6]
If you call this method https://github.com/trekawek/toxiproxy-java/blob/master/src/main/java/eu/rekawek/toxiproxy/model/ToxicList.java#L39 A null value is returned because this method is called https://github.com/trekawek/toxiproxy-java/blob/master/src/main/java/eu/rekawek/toxiproxy/model/ToxicType.java#L11 which returns always a `null`

It seems it misses the implementation of the method. I can provide PR fixing it.

**Comment by trekawek** [comment]
Thanks for noticing this @lordofthejars! Please provide the PR and I'll release the fixed version.

**Comment by lordofthejars** [comment]
Sorry, I have had no time to provide the PR :) Thanks for fixing

**Comment by trekawek** [comment]
No worries. I'm releasing the 2.1.1 right now, it'll contain the fix. Thanks for reporting the bug!
