### ISSUE TITLE
NullPointerException while getting non-existent proxy

### ISSUE THREAD

**Issue by dernasherbrezon** [trekawek/toxiproxy-java#8]
Steps to reproduce:

- execute the following code (proxy "test" should not exist):
```java
        ToxiproxyClient client = new ToxiproxyClient(env.getProperty("toxiproxy.baseUrl"),
                Integer.parseInt(env.getProperty("toxiproxy.port")));
        Proxy oldProxy = client.getProxy("test");
```

In logs:

```java
Caused by: java.lang.NullPointerException
	at eu.rekawek.toxiproxy.HttpClient.readResponse(HttpClient.java:109)
	at eu.rekawek.toxiproxy.HttpClient.get(HttpClient.java:67)
	at eu.rekawek.toxiproxy.HttpClient.get(HttpClient.java:62)
```

Expected:
* client.getProxy() method should return null if proxy doesn't exist

**Comment by trekawek** [comment]
While the NPE is certainly a bug, I think that throwing IOException would be a better option than returning null. toxiproxy-java is meant to be a thin client, translating the HTTP API into a Java API. Therefore error responses (like 404) should be translated into some kind of error, like Java exception.

In bbc47f3 I tried to make the error handling more resilient (no more NPEs). I hope it's acceptable for you.

BTW - which version of the Toxiproxy Server do you use? It's a bit strange that you don't get the correct JSON as a response for the request.

**Comment by dernasherbrezon** [comment]
Hi!

I'm using toxiproxy 2.1.0 and I've got 404. Which means proxy was not found rather than IO problems. Having IOException may be misleading...Maybe better create method getProxyOrNull? Null is pretty valid here. Nothing found, nothing returned.

**Comment by trekawek** [comment]
I can agree to getProxyOrNull :)
